### ISSUE TITLE
iMac需要怎么改呢

### ISSUE THREAD

**Issue by Shadowsuki** [tanenrumu/Arknights_Anti-addiction_Cheater#22]
我的电脑是iMac，不是很懂怎么搞
必须要装双系统吗

**Comment by DargonXuan** [comment]
https://github.com/DargonXuan/arknights-anti-addiction-cheater
详见 README.md ，已 Pull requests

**Comment by DargonXuan** [comment]
> 我的电脑是iMac，不是很懂怎么搞 必须要装双系统吗

 https://github.com/DargonXuan/arknights-anti-addiction-cheater 详见 README.md ，已 Pull requests

**Comment by long45343** [comment]
> 我的电脑是iMac，不是很懂怎么搞 必须要装双系统吗

https://github.com/tanenrumu/ArkNightsForMinor
可以用这个

**Comment by Shadowsuki** [comment]
已经搞定了，感谢大家
