### ISSUE TITLE
mitmproxy无法公网部署

### ISSUE THREAD

**Issue by DargonXuan** [tanenrumu/Arknights_Anti-addiction_Cheater#26]
未找到在python脚本中设置block_global=false

**Comment by DargonXuan** [comment]
https://github.com/DargonXuan/arknights-anti-addiction-cheater/blob/public-network/quick_start.sh
目前可以通过命令行设置，暂未找到有关block_global的方法

**Comment by edgexyz** [comment]
公网部署就是摆明了逆向...
想吃官司是一打一个准...

**Comment by DargonXuan** [comment]
> 如果真想公网可以 Nginx 反代

可以
